version: '3'
services:

  survero:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    command: python craft serve --host 0.0.0.0 -p 12000
    volumes:
      - ./:/usr/src/app/
      - ./volumes/zotero/:/usr/src/db/zotero
      - ./volumes/survero/:/usr/src/db/survero
    ports:
      - 12000:12000
